---
- name: Reboot Pi
  ansible.builtin.reboot:
    post_reboot_delay: 10
    reboot_timeout: 120

- name: Regenerate bootloader image
  ansible.builtin.command: ./mkscr
  args:
    chdir: /boot
  notify: Reboot Pi
  changed_when: true
