---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-lb
  namespace: rabbitmq-system
  annotations:
    metallb.universe.tf/loadBalancerIPs: 10.0.2.15
spec:
  selector:
    app.kubernetes.io/name: rabbitmq
  ports:
    - name: amqp
      protocol: TCP
      port: 5672
      targetPort: 5672
    - name: management
      protocol: TCP
      port: 15672
      targetPort: 15672
    - name: mqtt
      protocol: TCP
      port: 1883
      targetPort: 1883
    - name: prometheus
      protocol: TCP
      port: 15692
      targetPort: 15692
  type: LoadBalancer
